Repository sora-grayscale/ft_irc, pull requests merged in 2024-03, with the labels that each got.

#112 Feat/110 create executecommand function
  .gitignore
  Makefile
  documents/echo-server-test.cpp
  inc/CommandHandler.hpp
  inc/Replies.hpp
  inc/Server.hpp
  inc/User.hpp
  src/CommandHandler.cpp
  src/CommandHandler_handleCommand.cpp
  src/CommandHandler_parseMessage.cpp
  src/Replies.cpp
  src/Server.cpp
  src/Server_run.cpp
  src/User.cpp
Labels: enhancement

#137 Feat/47 create command join message
  Makefile
  inc/Channel.hpp
  inc/CommandHandler.hpp
  inc/Replies.hpp
  inc/Server.hpp
  inc/User.hpp
  src/Channel.cpp
  src/CommandHandler.cpp
  src/CommandHandler_Join.cpp
  src/CommandHandler_debug.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
  src/Server.cpp
  src/User.cpp
Labels: enhancement

#146 Feat/48 create command part message
  Makefile
  inc/Channel.hpp
  inc/CommandHandler.hpp
  inc/Replies.hpp
  src/Channel.cpp
  src/CommandHandler_Part.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
Labels: enhancement

#156 Fix/155 nick error
  src/CommandHandler.cpp
Labels: bug

#157 Feat/51 create command names message
  Makefile
  inc/CommandHandler.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/CommandHandler.cpp
  src/CommandHandler_Names.cpp
  src/CommandHandler_Topic.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
  src/Server.cpp
  src/Server_run.cpp
Labels: enhancement

#164 [feat]: #52 LISTコマンドの実装
  Makefile
  inc/Channel.hpp
  inc/CommandHandler.hpp
  src/Channel.cpp
  src/CommandHandler_List.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
Labels: enhancement

#168 Feat/73 create command who query
  Makefile
  inc/Channel.hpp
  inc/CommandHandler.hpp
  inc/Replies.hpp
  inc/Server.hpp
  inc/User.hpp
  src/Channel.cpp
  src/CommandHandler_Join.cpp
  src/CommandHandler_List.cpp
  src/CommandHandler_Who.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
  src/Server.cpp
  src/User.cpp
Labels: enhancement

#169 Feat/53 create command invite message
  Makefile
  inc/CommandHandler.hpp
  inc/Replies.hpp
  inc/Server.hpp
  src/CommandHandler_Invite.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
  src/Server.cpp
Labels: enhancement

#171 Feat/75 create command whowas
  Makefile
  inc/CommandHandler.hpp
  inc/Replies.hpp
  inc/Server.hpp
  src/CommandHandler_Invite.cpp
  src/CommandHandler_Whois.cpp
  src/CommandHandler_Whowas.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
  src/Server.cpp
Labels: enhancement

#172 Feat/54 create command kick command
  Makefile
  inc/Channel.hpp
  inc/CommandHandler.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/CommandHandler_Kick.cpp
  src/CommandHandler_handleCommand.cpp
Labels: enhancement

#177 USER MODE
  Makefile
  inc/CommandHandler.hpp
  inc/Replies.hpp
  src/Channel.cpp
  src/CommandHandler_Mode.cpp
  src/CommandHandler_Nick.cpp
  src/CommandHandler_handleCommand.cpp
  src/Replies.cpp
Labels: enhancement

#180 Feat/178 create channel mode
  inc/Channel.hpp
  inc/CommandHandler.hpp
  inc/Replies.hpp
  src/Channel.cpp
  src/CommandHandler_Mode.cpp
  src/CommandHandler_Whowas.cpp
  src/Replies.cpp
Labels: enhancement

#185 [fix]: #181 channel mode k error
  src/CommandHandler_Join.cpp
Labels: bug

#184 [WIP][fix]: #182 プルリクエストレビューに基づくコードの改善
  inc/Channel.hpp
  inc/CommandHandler.hpp
  inc/Server.hpp
  src/Channel.cpp
  src/CommandHandler_Error.cpp
  src/CommandHandler_Kill.cpp
  src/CommandHandler_Nick.cpp
  src/CommandHandler_Notice.cpp
  src/CommandHandler_Ping.cpp
  src/CommandHandler_Pong.cpp
  src/CommandHandler_Privmsg.cpp
  src/CommandHandler_Quit.cpp
  src/Server.cpp
  src/Server_run.cpp
Labels: In Progress

#193 Bug/191 if password command not send irc is bug
  inc/CommandHandler.hpp
  inc/User.hpp
  src/CommandHandler_Pass.cpp
  src/CommandHandler_handleCommand.cpp
  src/User.cpp
Labels: bug

#197 [fix]: #196 トピックコマンドのチャンネルモードフラグチェックの追加
  src/CommandHandler_Topic.cpp
Labels: bug

#203 [fix]: #202 fix Invite command
  inc/Server.hpp
  src/CommandHandler_Invite.cpp
  src/CommandHandler_Topic.cpp
  src/Server_run.cpp
Labels: bug
